### ISSUE TITLE
Technical suggestions

### ISSUE THREAD

**Issue by oschwab** [MarshP/dcss-morgue-analyser#6]
Here's just a bunch of suggestions I get from reading  the source code

- receive parameters from command line  (see [how I did it in death stats](https://github.com/oschwab/dcss-morgue-analyser/blob/67878097c8b8d857632f822726e4e078b2709c79/dcss_morgue_analyser/death_stats.py#L292)  )

- separate information acquisition from presentation : store the information extracted from morgue in data structures ( classes or lists or tuple , or whatever) , and later pass it to a (class,function) that will present it (in Markdown for the moment, but we could later imagine a GUI, raw text, HTML, or other formats )

**Comment by MarshP** [comment]
Okay, first I intend to do is the second. I want to refactor anyway to make the functions less huge.

**Comment by oschwab** [comment]
Hey,

If you want , I prepare the first option on my fork.
the plan : a Configuration object ( containing morgue path, output type , ...)  , filled by command line, that you can pass around in every functions / objects.

**Comment by MarshP** [comment]
Yes! I'm going to be out of action for quite a while. Maybe even much of the winter. Feel free to do as you will!

**Comment by oschwab** [comment]
As you want, @MarshP , but may be that if your first intention was to learn python, It would be better if I create my own project on my side ?

**Comment by MarshP** [comment]
Yes. Do what you will with my code, such as it is. Later I'll borrow from yours!
